# Generated by Django 5.2.7 on 2025-10-15 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRegistration',
            new_name='EventApplication',
        ),
        migrations.RenameField(
            model_name='eventapplication',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='eventapplication',
            unique_together={('user', 'event')},
        ),
    ]
