# Generated by Django 5.2.7 on 2025-10-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_eventregistration_eventapplication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventapplication',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='eventapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Sample Event', max_length=100),
            preserve_default=False,
        ),
    ]
