# Generated by Django 5.2.7 on 2025-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_user_eventapplication_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Main Campus', max_length=200),
            preserve_default=False,
        ),
    ]
