# Generated by Django 5.2.7 on 2025-10-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('COMPETITION', 'Competition'), ('FAIR', 'Fair'), ('SEMINAR', 'Seminar'), ('CONFERENCE', 'Conference')], default='COMPETITION', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='password_required',
            field=models.BooleanField(default=False),
        ),
    ]
