# Generated by Django 5.2.7 on 2025-10-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_galleryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryItem',
        ),
    ]
